// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

function fst(param) {
  return param[0];
}

var Crisis = /* @__PURE__ */Caml_exceptions.create("Demo-StaticAccessControl.Crisis");

function panic(param) {
  throw {
        RE_EXN_ID: Crisis,
        Error: new Error()
      };
}

throw {
      RE_EXN_ID: Crisis,
      Error: new Error()
    };

console.log(undefined);

exports.fst = fst;
exports.Crisis = Crisis;
exports.panic = panic;
/*  Not a pure module */
