// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function create(x) {
  return {
          contents: x
        };
}

function set(t, x) {
  t.contents = x;
  
}

function get(t) {
  return t.contents;
}

var Ref = {
  create: create,
  set: set,
  get: get
};

function readonly(x) {
  return x;
}

var IRef = {
  create_immutable: create,
  create_readwrite: create,
  readonly: readonly,
  set: set,
  get: get
};

function sumrefs(reflist) {
  return List.fold_left((function (prim, prim$1) {
                return prim + prim$1 | 0;
              }), 0, List.map(get, reflist));
}

function increfs(reflist) {
  return List.iter((function (r) {
                r.contents = r.contents + 1 | 0;
                
              }), reflist);
}

function readonly$1(x) {
  return x;
}

var IRefP = {
  create: create,
  set: set,
  get: get,
  readonly: readonly$1
};

var r = {
  contents: 3
};

console.log(r);

console.log("readonly", r);

var r$1 = {
  contents: 3
};

console.log(r$1);

console.log(r$1.contents);

exports.Ref = Ref;
exports.IRef = IRef;
exports.sumrefs = sumrefs;
exports.increfs = increfs;
exports.IRefP = IRefP;
exports.r = r$1;
/*  Not a pure module */
