// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ref$StaticAccessControl = require("./Ref.bs.js");

function readonly(x) {
  return x;
}

var IRef = {
  create: Ref$StaticAccessControl.create,
  set: Ref$StaticAccessControl.set,
  get: Ref$StaticAccessControl.get,
  readonly: readonly
};

var r = Ref$StaticAccessControl.create(3);

console.log(r);

var r$1 = Ref$StaticAccessControl.create(3);

console.log(r$1);

console.log(Ref$StaticAccessControl.get(r$1));

exports.IRef = IRef;
exports.r = r$1;
/* r Not a pure module */
