// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function create(x) {
  return {
          contents: x
        };
}

function set(t, x) {
  t.contents = x;
  
}

function get(t) {
  return t.contents;
}

exports.create = create;
exports.set = set;
exports.get = get;
/* No side effect */
