// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function create(x) {
  return {
          contents: x
        };
}

function set(t, x) {
  t.contents = x;
  
}

function get(t) {
  return t.contents;
}

var Ref = {
  create: create,
  set: set,
  get: get
};

function $$import(x) {
  return x;
}

var RORef = {
  $$import: $$import,
  get: get
};

function readonly(x) {
  return x;
}

var PRef = {
  create: create,
  set: set,
  get: get,
  readonly: readonly
};

function sumrefs(reflist) {
  return List.fold_left((function (prim, prim$1) {
                return prim + prim$1 | 0;
              }), 0, List.map(get, reflist));
}

function increfs(reflist) {
  return List.iter((function (r) {
                r.contents = r.contents + 1 | 0;
                
              }), reflist);
}

exports.Ref = Ref;
exports.RORef = RORef;
exports.PRef = PRef;
exports.sumrefs = sumrefs;
exports.increfs = increfs;
/* No side effect */
